---
services:
  postfix:
    image: docker.io/mwader/postfix-relay:1.1.39
    environment:
      - POSTFIX_myhostname=postfix
    volumes:
      - ./config/postfix-relay/main.cf:/etc/postfix/main.cf:ro
      - ./config/postfix-relay/sasl_passwd:/etc/postfix/sasl_passwd:rw
      - postfix_data:/etc/postfix
    restart: unless-stopped

volumes:
  postfix_data: