version: '3.8'

services:
  homepage:
    image: ${HOMEPAGE_IMAGE}
    container_name: ${HOMEPAGE_CONTAINER_NAME}
    ports:
      - ${HOMEPAGE_PORT}:3000
    env_file: .env
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    labels:
      - traefik.enable=true
      - traefik.http.services.homepage.loadbalancer.server.port=80
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.rule=Host(`${TRAEFIK_HOSTNAME}`)
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=${TRAEFIK_CERTRESOLVER}
      - traefik.http.routers.homepage.service=homepage
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true