---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: xl
    format:
      timeStyle: short

- unifi_console:
    url: "{{EPAGE_VAR_UNIFI_NETWORK_URL}}"
    username: "{{EPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
    password: "{{EPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
    # site: Dom